Repository YoungVision-eV/website, pull requests merged in 2024-06, with the labels that each got.

#187 fix(website): fix some layout issues on event pages
  astro.config.mjs
  src/data/events.ts
  src/pages/events/[slug].astro
Labels: 1 min review

#198 Use correct alt description for the event calendar covers
  src/components/Calendar.svelte
  src/data/events.ts
Labels: 1 min review

#199 test(website): add a test for event page
  src/data/events.ts
  tests/events.spec.ts
  tests/events.spec.ts-snapshots/Event-Page-screenshot-1-Mobile-Chrome-linux.png
  tests/events.spec.ts-snapshots/Event-Page-screenshot-1-chromium-linux.png
  tests/events.spec.ts-snapshots/Event-Page-screenshot-1-firefox-linux.png
Labels: tests, 1 min review, screenshots

#221 use autofix.ci
  .github/workflows/autofix.yml
Labels: 1 min review

#223 chore(tools)!: Move to pnpm v9
  .github/workflows/autofix.yml
  .github/workflows/checks.yml
  .github/workflows/playwright.yml
  pnpm-lock.yaml
Labels: 1 min review

#245 fix(website): #244 sort events
  src/data/events.ts
Labels: 1 min review

#225 Revert "chore(deps): update dependency eslint to v9 (#218)"
  .eslintignore
  .eslintrc.cjs
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/components/Button.astro
Labels: dependencies, 1 min review

#249 fix(website): #164 use fake insta posts in preview deployment
  src/data/instagram.ts
Labels: 1 min review

#224 ci(tools): clean up github actions
  .github/workflows/checks.yml
  .github/workflows/eslint-matcher.json
  .github/workflows/playwright.yml
Labels: 5 min review
