Repository YoungVision-eV/website, pull requests merged in 2024-05, with the labels that each got.

#165 Remove Bauwoche, add Gathering to calendar
  src/data/events.ts
Labels: 1 min review

#175 140 get calendar data from cms
  package.json
  pnpm-lock.yaml
  src/data/events.ts
  src/data/payload-types.ts
  tailwind.config.mjs
Labels: dependencies, 20 min review

#183 refactor(website): #41 use correct headings
  src/components/Testimonials.svelte
  src/components/index/Events.astro
  src/components/index/Instagram.astro
  src/components/index/ReadMore.astro
Labels: 1 min review

#184 fix(website): #167 Highlight top level navbar elements for sub pages
  src/components/Navbar.svelte
  tests/events.spec.ts-snapshots/Bauwoche-2024-screenshot-1-firefox-linux.png
Labels: tests, 1 min review, screenshots
