Repository YoungVision-eV/website, pull requests merged in 2024-07, with the labels that each got.

#263 build(website): 164 remove instagram integration
  src/pages/index.astro
  tests/index.spec.ts-snapshots/index-page-screenshot-1-Mobile-Chrome-linux.png
  tests/index.spec.ts-snapshots/index-page-screenshot-1-chromium-linux.png
  tests/index.spec.ts-snapshots/index-page-screenshot-1-firefox-linux.png
  tests/index.spec.ts-snapshots/testimonials-can-be-scrolled-1-Mobile-Chrome-linux.png
  tests/index.spec.ts-snapshots/testimonials-can-be-scrolled-1-chromium-linux.png
  tests/index.spec.ts-snapshots/testimonials-can-be-scrolled-1-firefox-linux.png
Labels: tests, 1 min review, screenshots

#293 Fix deployment
  package.json
  pnpm-lock.yaml
Labels: dependencies, 1 min review

#290 Fix event duration when start and time are in diffrent months
  src/pages/events/[slug].astro
Labels: 1 min review
