Repository YoungVision-eV/website, pull requests merged in 2024-03, with the labels that each got.

#63 set up better commits
  .better-commits.json
  README.md
Labels: 5 min review

#72 perf(app): #33 optimize all images in what we do section
  .husky/post-checkout
  src/components/about-us/Exercises.svelte
  src/components/about-us/WhatWeDo.astro
  src/components/about-us/WhatWeDo.svelte
  src/data/exercises.ts
  src/pages/about-us.astro
  tests/about-us.spec.ts
Labels: tests, 5 min review

#76 chore(tools): Use published git-format-staged
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  scripts/git-format-staged.py
Labels: dependencies, 1 min review

#73 Refactor Donation methods
  package.json
  pnpm-lock.yaml
  src/assets/icons/CircleDecorations.svg
  src/assets/icons/DonationBoxHand.svg
  src/assets/icons/HandShake.svg
  src/assets/icons/HeadLightbulb.svg
  src/components/support-us/DonationMethodList.svelte
  src/components/support-us/DonationMethodTabs.svelte
  src/components/support-us/DonationMethods.astro
  src/components/support-us/DonationMethods.svelte
  src/components/support-us/markdown/List.svelte
  src/components/support-us/markdown/ListItem.svelte
  src/components/support-us/markdown/Paragraph.svelte
  src/data/donations.ts
  src/pages/support-us.astro
  tests/support-us.spec.ts
Labels: dependencies, tests, 1 min review

#86 update bauwochen assets
  public/Bauwoche Zeitplan.pdf
  public/Bauwoche-Wochenplan.png
  src/assets/events/bauwoche-2024/Bauwoche Zeitplan.svg
  src/pages/events/bauwoche-2024.astro
  tests/events.spec.ts
  tests/events.spec.ts-snapshots/Bauwoche-2024-screenshot-1-chromium-linux.png
  tests/events.spec.ts-snapshots/Bauwoche-2024-screenshot-1-firefox-linux.png
Labels: tests, 1 min review, screenshots

#90 Add All Contributors
  README.md
Labels: 1 min review

#102 Han2 ro/test/64 make tests independent from events
  .github/workflows/playwright.yml
  playwright.config.ts
  src/data/events.ts
  tests/index.spec.ts-snapshots/index-page-screenshot-1-Mobile-Chrome-linux.png
  tests/index.spec.ts-snapshots/index-page-screenshot-1-chromium-linux.png
  tests/index.spec.ts-snapshots/index-page-screenshot-1-firefox-linux.png
  tests/projects.spec.ts-snapshots/Projects-page-screenshot-1-Mobile-Chrome-linux.png
  tests/projects.spec.ts-snapshots/Projects-page-screenshot-1-chromium-linux.png
  tests/projects.spec.ts-snapshots/Projects-page-screenshot-1-firefox-linux.png
  tests/projects.spec.ts-snapshots/Reselect-for-all-1-Mobile-Chrome-linux.png
  tests/projects.spec.ts-snapshots/Reselect-for-all-1-chromium-linux.png
  tests/projects.spec.ts-snapshots/Reselect-for-all-1-firefox-linux.png
  tests/projects.spec.ts-snapshots/Select-members-only-1-Mobile-Chrome-linux.png
  tests/projects.spec.ts-snapshots/Select-members-only-1-chromium-linux.png
  tests/projects.spec.ts-snapshots/Select-members-only-1-firefox-linux.png
Labels: tests, 5 min review, screenshots

#78 feat(app): #38 update posts from instagram API
  astro.config.mjs
  src/components/index/Instagram.astro
  src/data/instagram.ts
Labels: 5 min review

#103 Han2 ro/test/64 make test independet form yearly events
  src/data/events.ts
  tests/about-us.spec.ts
  tests/about-us.spec.ts-snapshots/About-Us-page-screenshot-1-chromium-linux.png
  tests/fixtures.ts
  tests/projects.spec.ts
  tests/projects.spec.ts-snapshots/Projects-page-screenshot-1-Mobile-Chrome-linux.png
  tests/projects.spec.ts-snapshots/Projects-page-screenshot-1-chromium-linux.png
  tests/projects.spec.ts-snapshots/Projects-page-screenshot-1-firefox-linux.png
  tests/projects.spec.ts-snapshots/Reselect-for-all-1-Mobile-Chrome-linux.png
  tests/projects.spec.ts-snapshots/Reselect-for-all-1-chromium-linux.png
  tests/projects.spec.ts-snapshots/Reselect-for-all-1-firefox-linux.png
  tests/projects.spec.ts-snapshots/Select-members-only-1-Mobile-Chrome-linux.png
  tests/projects.spec.ts-snapshots/Select-members-only-1-chromium-linux.png
  tests/projects.spec.ts-snapshots/Select-members-only-1-firefox-linux.png
Labels: tests, 5 min review, screenshots

#111 Fix README formatting
  .all-contributorsrc
  README.md
Labels: 1 min review

#114 chore(tools): run pnpm update
  pnpm-lock.yaml
Labels: 10 min review

#116 chore(tools): update all eslint plugins
  package.json
  pnpm-lock.yaml
Labels: dependencies, 5 min review
